#!/bin/bash

# Please don't change this.
MAX_POINTS=150

# TODO 1: Function check for task 1
test_walsh() {
	n_tests=25
	src_names=(walsh.c walsh.cpp Walsh.java)
	tests=($(seq 0 $(($n_tests - 1))))
	points=($(printf '1.0 %.0s' $(seq 0 $(($n_tests - 1)))))
	pmax=25

	run_problem walsh 1
}

# TODO 2: Function check for task 2
test_statistics() {
	n_tests=25
	src_names=(statistics.c statistics.cpp Statistics.java)
	tests=($(seq 0 $(($n_tests - 1))))
	points=($(printf '1.0 %.0s' $(seq 0 $(($n_tests - 1)))))
	pmax=25

	run_problem statistics 2
}

# TODO 3: Function check for task 3
test_prinel() {
	n_tests=30
	src_names=(prinel.c prinel.cpp Prinel.java)
	tests=($(seq 0 $(($n_tests - 1))))
	points=($(printf '1.0 %.0s' $(seq 0 $(($n_tests - 1)))))
	pmax=30

	run_problem prinel 3
}

# TODO 4: Function check for task 4
test_crypto() {
	n_tests=35
	src_names=(crypto.c crypto.cpp Crypto.java)
	tests=($(seq 0 $(($n_tests - 1))))
	points=($(printf '1.0 %.0s' $(seq 0 $(($n_tests - 1)))))
	pmax=35

	run_problem crypto 4
}

test_regele() {
	n_tests=25
	src_names=(regele.c regele.cpp Regele.java)
	tests=($(seq 0 $(($n_tests - 1))))
	points=($(printf '1.0 %.0s' $(seq 0 $(($n_tests - 1)))))
	pmax=25

	run_problem regele 5
}

# TODO 5: Put your tasks in this function
test_homework() {
	if [[ "$1" = "1" || "$1" = "walsh" ]]; then
        test_walsh
	elif [[ "$1" = "2" || "$1" = "statistics" ]]; then
        test_statistics
	elif [[ "$1" = "3" || "$1" = "prinel" ]]; then
        test_prinel
	elif [[ "$1" = "4" || "$1" = "crypto" ]]; then
		test_crypto
    elif [[ "$1" = "5" || "$1" = "regele" ]]; then
        test_regele
	elif [[ "$1" = "cs" ]]; then
		echo "skip running tests"
	else
		test_walsh
		test_statistics
		test_prinel
		test_crypto
		test_regele
	fi
}

# TODO 6:Define bonus task
BONUS_TASK=regele

# Please don't change this.
source "$(dirname "{0}")"/_utils/base_check.sh